spring.application.name=spring-basic

spring.datasource.url=jdbc:mysql://localhost:3306/spring_basic?serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=wlals12!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret-key=${JWT_SECRET}